### ISSUE TITLE
'Gradients' source plugin, and 'Add' mixer plugin, missing from repo?

### ISSUE THREAD

**Issue by discopatrick** [resolume/ffgl#2]
Hi there,

I've been looking through the Xcode project. It would seem that there were some originally some additional examples of FFGL plugins in this project - one called Gradients (a source plugin) and one called Add (a mixer plugin).

It would be great to see examples of how these plugins would be written for FFGL too.

**Comment by rsodre** [comment]
Me too!

**Comment by rsodre** [comment]
I found the Add sources here:
[](https://github.com/Natspir/ffgl/tree/master/source/plugins/Add)

And Gradients (maybe) here:
https://github.com/robksawyer/FFGLSDK/tree/master/Source/FFGLPlugins/FFGLGradients

**Comment by discopatrick** [comment]
Thanks @rsodre !

**Comment by rsodre** [comment]
I added them to my fork: https://github.com/rsodre/ffgl
Note that the Gradients example was made for FF 1.0, so there's no shaders in it, but with some adaptations it's working now.

**Comment by jorisdejong** [comment]
@rsodre if you like, you can put in a pull request for Gradients. I'll update the VS project. I'm working on cleaning up the pull request from @Natspir for Add.

**Comment by rsodre** [comment]
ok, done!

**Comment by jorisdejong** [comment]
Both Add and Gradients crash when running more than one instance of the plugin.

**Comment by jorisdejong** [comment]
Pushed a fix for the default implementation of GetParameterDisplay. Gradients and Add should work on OSX

**Comment by jorisdejong** [comment]
VS2017 project is in. Fireworks source added as advanced example
