### ISSUE TITLE
SetParamInfo() order

### ISSUE THREAD

**Issue by rsodre** [resolume/ffgl#20]
When we add a param using SetParamInfo(), what's used by the host as key to keep track of the param, the ID or the name? Will I have problems if I update an existing plugin, adding a new parameter in between existent params, when reading saved projects?

Example, I have a plugin with 3 params:
- 0: A
- 1: B
- 2: C

And I add a new parameter in between, because contextually I don't want it to be displayed at the bottom:
- 0: A
- 1: X
- 2: B
- 3: C

**Comment by jorisdejong** [comment]
When serializing values in Resolume, we refer to the param by name. Precisely for the reason you describe

FFGL itself will refer to the param by index of creation order for the getter and setter functions, ie SetFloatParameter( int index, float value )

**Comment by jorisdejong** [comment]
I'm assuming this issue can be closed, as there is no action that needs be taken?
