### ISSUE TITLE
Don't waste your time - these are for Resolume 7 which doesn't exist.

### ISSUE THREAD

**Issue by tomspace** [resolume/ffgl#27]
It's a shame there is not one single example which works in Resolume 6, Nobody can make plugins for it because the example SDK has been "upgraded" for a release which is years away. 

This is really frustrating for people trying to start out making plugins.

**Comment by smokris** [comment]
@tomspace See [the ffgl1.5 branch](https://github.com/resolume/ffgl/tree/ffgl1.5) for examples that should work on Resolume 6 and other hosts.

**Comment by tomspace** [comment]
sorry for the poor tone of my message, just had a frustrating day with this! Gonna try the 1.5 branch now in visual studio 15 which seems more likely to work than the 19 i have been using :)

**Comment by jorisdejong** [comment]
Added readme c5c0abd
