### ISSUE TITLE
Conflicting definitions of GLhandleARB in GLee.h and FFGLExtensions.h

### ISSUE THREAD

**Issue by spxl** [resolume/ffgl#29]
These handles are not used for math, so it shouldn't matter a lot, however there is potential for "overflow" if copying to/from some other variable type. Meanwhile, I have to change one of them to compile. Unsigned seems like the way to go!

Curiously, I noticed that the files FFGLExtensions.cpp and FFGLExtensions.h are not included in the Visual Studio projects I am working on, so searching the FFGL solution doesn't find the clashing reference, however the compiler sure notices when #include "FFGLExtensions.h" appears in a header file, in my case brought in from the FFGLGradients example project from the FFGL SDK v1.5 (not from the Resolume repository).

https://github.com/resolume/ffgl/blob/d7b1003af6137919a8ce3ced60a64fad011b6ee1/source/lib/glee/GLee.h#L765

https://github.com/resolume/ffgl/blob/d7b1003af6137919a8ce3ced60a64fad011b6ee1/source/lib/ffgl/FFGLExtensions.h#L302

**Comment by MennoVink** [comment]
We dont use FFGLExtensions anymore. Since FFGL2.0 we're using glload because it can load OpenGL 4.1 extensions. glload replaces both glee and FFGLExtensions
