### ISSUE TITLE
glGetProgramInfoLog() incorrectly called to check shader compilation errors

### ISSUE THREAD

**Issue by spxl** [resolume/ffgl#30]
When glCompileShader() fails, glGetProgramInfoLog() is being called to access the error message:

https://github.com/resolume/ffgl/blob/d7b1003af6137919a8ce3ced60a64fad011b6ee1/source/lib/ffgl/FFGLShader.cpp#L120

The returnedLength variable is uninitialised and the following log[returnedLength] = 0 can do something bad / throw an exception, in addition to the log message not being obtained.

Replaced with glGetShaderInfoLog() and successfully received error messages relating to my invalid fragment shader code.

Same deal for the vertex shader:

https://github.com/resolume/ffgl/blob/d7b1003af6137919a8ce3ced60a64fad011b6ee1/source/lib/ffgl/FFGLShader.cpp#L161

-subpixel

**Comment by ResolumeMenno** [comment]
Where do you get this version of that file?

glGetShaderInfoLog is supposed to be used for shader compilation errors
glGetProgramInfoLog is supposed to be used for program linking errors

The version of this file on the master branch is doing this correctly so this issue has already been fixed?

**Comment by spxl** [comment]
Sorry I didn't mention it is from the ffgl1.5 branch (I used the "Reference in new issue" / 
and "Copy permalink" options viewing on the website).

https://github.com/resolume/ffgl/blob/ffgl1.5/source/lib/ffgl/FFGLShader.cpp

I note in the main README.md this message:

To compile plugins for currently available hosts (Resolume, VDMX, COGE, Isadora, Magic Music Visuals), switch to the FFGL1.5 branch: https://github.com/resolume/ffgl/tree/ffgl1.5

Should this not be fixed in the version that people are using?

**Comment by ResolumeMenno** [comment]
Ah i see your point, the ffgl1.5 branch should keep working optimally for hosts that still use that version. 
Can you create a PR for the change you've made?

**Comment by spxl** [comment]
I haven't been using git, so this could take a while. On a hypothetical maybe-one-dayTODO list.

**Comment by MennoVink** [comment]
We've removed FFGL1.6 and FFGL2.0 from this repository. We aren't supporting it anymore and none of the other host developers are present to provide the maintenance required. As such this issue is no longer relevant.
