### ISSUE TITLE
FFGLGradients

### ISSUE THREAD

**Issue by colorcompiler** [resolume/ffgl#31]
Trying out the FFGL Gradients example as a source in Layer 1 (Resolume 6 version 61.3. rev63441), it does only rarely update when chaning any parameter. Putting it in layer 2 and having something that is animated in layer 1 it updates when a new parameter is chosen as expected. 
So my questions: 
Is ProcessOpenGL not always called when a new parameter is set?

**Comment by jorisdejong** [comment]
ProcessOpenGL is called every time the host renders. Basically it's your draw call.

When you can change a parameter value in the host, the host calls SetParamInfo with the index and value of the parameter you are changing.

**Comment by colorcompiler** [comment]
The ProcessOpenGL is called constantly (as the attached debugger shows) but why does not layer 1 show the output of the FFGLGradient example (only FFGLGradient example in Layer1, nothing on the following layers)  (ffgl1.5 github branch )  
I have checked it on Mac OSX and on Windows builds (with Arena and Avenue versions) it is not displayed in layer 1, whereas the FFGLFireworks example and the normal Gradient is displayed correctly as expected. I have included in ProcessOpenGL glClearColor() and glClear() at the beginning and glFinish() or glFlush() at the end (no impact).
FFGLGradient example works always correctly once it is in Layer 2 and some Video or another source is in Layer1.

**Comment by jorisdejong** [comment]
Yup, that looks broken... Weird

**Comment by jorisdejong** [comment]
Rewrote the example to use a shader

**Comment by jorisdejong** [comment]
fixed includes on both OSX and Windows
