### ISSUE TITLE
FFGLShader::FindUniform() wrapper returns GLuint instead of GLint (FFGL1.5)

### ISSUE THREAD

**Issue by spxl** [resolume/ffgl#34]
In the FFGL1.5 branch...

https://github.com/resolume/ffgl/blob/82d76cc890a054847a5e1aff398964941b7de960/source/lib/ffgl/FFGLShader.cpp#L185

glGetUniformLocation() return type is GLint, and returns -1 if the uniform is not found.

The wrapper function FFGLShader::FindUniform() return type is GLuint.

This makes a mess in calling code if you want to check that the uniform was found.

**Comment by MennoVink** [comment]
We've removed FFGL1.6 (what you call 1.5) and FFGL2.0 from this repository. We aren't supporting it anymore and none of the other host developers are present to provide the maintenance required. As such this issue is no longer relevant.
