### ISSUE TITLE
after succesfull OSX build plugin works only in Resolume

### ISSUE THREAD

**Issue by neonm3** [resolume/ffgl#4]
should work in all other software as that's the point isn't it? ;/

**Comment by jorisdejong** [comment]
Working in Coge and VDMX. Closing as 'works for me' until further info is provided.

**Comment by neonm3** [comment]
sorry my bad in fact it does work perfectly - I wasn't aware for most of other software freeframes have to be in ~/Library/Graphics rather then in their proprietary Application directory.
