### ISSUE TITLE
cpu glubyte array to texture

### ISSUE THREAD

**Issue by piotrus04** [resolume/ffgl#46]
Hi it is not an issue. Just asking for an example how i can update the content of a texture from the cpu, in the processopengl method. I want to be able to load a picture in a texture, generate cpu side algorithm and other sort of cpu special code. Anybody could put an example ? 

all the best

**Comment by ResolumeMenno** [comment]
Yes you will want to use OpenGL's glTexImage2D function.
This tutorial contains a description on how to load textures: http://www.opengl-tutorial.org/beginners-tutorials/tutorial-5-a-textured-cube/
