### ISSUE TITLE
Add support for parameter groups

### ISSUE THREAD

**Issue by ResolumeMenno** [resolume/ffgl#48]
We should add support to the ffgl sdk to enable plugins to make use of a host's ability to support grouping several parameters into a more simple interface. For example Resolume allows grouping scaleX, scaleY, scaleZ and scaleALL parameters into a single group where a collapsed group would enable you to edit the scaleALL parameter directly but an uncollapsed group enables you to control each parameter individually.
Adding support for this in the ffgl sdk will enable plugins to create similar groupings with the result of easier to understand initial ui while still allowing in-depth control for the more advanced users of that plugin.

**Comment by MennoVink** [comment]
Implemented in FFGL2.2. Call SetParamGroup
