### ISSUE TITLE
Support separators for option parameters

### ISSUE THREAD

**Issue by ResolumeMenno** [resolume/ffgl#49]
Sometimes plugin developers want to have option parameters containing several categories of options. With native ui they're used to adding separators in between those categories. We should add support for plugins to add options that have to be interpreted by the host as separators.

**Comment by MennoVink** [comment]
To be released in FFGL 2.2. Particles example shows how it's done.
eg:
	SetParamElementInfo( PID_MAX_AGE, 0, "0.5 beats", 0.5f );
	AddElementSeparator( PID_MAX_AGE, 1 );
	SetParamElementInfo( PID_MAX_AGE, 1, "1 beat", 1.0f );
This adds a separator in front of the "1 beat" option.
