### ISSUE TITLE
GL calls from SetFloatParameter() cause crash.

### ISSUE THREAD

**Issue by perrelet** [resolume/ffgl#5]
This issue can be easily reproduced from the included AddSubract project example.

Declare:

`GLuint newVertexShader;`

Add an event button:

`#define FFPARAM_BUTTON		 (3)
SetParamInfo(FFPARAM_BUTTON, "BUTTON", FF_TYPE_EVENT, 0.0f);`

Call glCreateShader() from the SetFloatParameter function:

```
FFResult AddSubtract::SetFloatParameter(unsigned int dwIndex, float value){
	switch (dwIndex){
	case FFPARAM_BUTTON:
		newVertexShader = glCreateShader(GL_VERTEX_SHADER);
		break;
	case FFPARAM_BrightnessR:
		m_BrightnessR = value;
		break;
	case FFPARAM_BrightnessG:
		m_BrightnessG = value;
		break;
	case FFPARAM_BrightnessB:
		m_BrightnessB = value;
		break;
	default:
		return FF_FAIL;
	}
	return FF_SUCCESS;
}
```

Run the plugin, click the button and boom! - the process dies... Any ideas?

I worked around this issue by setting bool flags that are checked during each ProcessOpenGL call. All the GL stuff appears to work fine from there... This issue did not exist with previous code in FFGL1.5 - any ideas?

Thanks and Fractal Blessings.

**Comment by jorisdejong** [comment]
SetFloatParam is being called continuously while you hold the button down, which means you're constantly deleting the shader and creating a new one. Accessing it on ProcessOpenGL while this is happening is not safe. 

For ParamEvents, ideally you want to implement OnClick and OnRelease functions that get called once, by checking against the previous state. To be completely safe, you'll then want to use these functions to set a variable that gets checked on the render call.

**Comment by perrelet** [comment]
Thanks for the reply J,
Setting up onX event-watchers has been my solution, and works fine.
However FYI - when I was bug checking this issue I found that the critical crash occurs the instant a gl call is made from within SetFloatParameter, not when ProcessOpenGL is fired.
i.e in the above code snippet newVertexShader is **not** a variable used elsewhere (such as ProcessOpenGL) - rather, it is a standalone test call that brings the entire house of cards tumbling down! This certainly wasn't the case in FFGL 1.5 so I do indeed have to wonder where the instability is...

**Comment by jorisdejong** [comment]
This repo is still FFGL1.5. It just has been cleaned up, and now has a minor bug fix for displaying parameters 64 bit. Nothing has changed for making OpenGL calls.

I assume you are experiencing these crashes in Resolume 6?

**Comment by jorisdejong** [comment]
We had some internal discussion about this, and changing the OpenGL state anywhere else than the render thread is not a good idea.
