### ISSUE TITLE
Add support for value change events

### ISSUE THREAD

**Issue by ResolumeMenno** [resolume/ffgl#50]
With the introduction of visibility change events some care has already been taken to support other kinds of events. The most useful other event we could support is the value change event. This enables a plugin to change the value of one of it's parameter in response to the value of another parameter that was changed. This is useful when a plugin has some internal state it wants to keep consistent with it's parameter's values. For example take a plugin providing left, top, right, bottom parameters. Maybe the plugin wants to keep the size of the indicated area unchanged. When it receives a value change for the left parameter it could automatically adjust the right parameter and send a value change to the host. The host would pick up that the right parameter has changed and reflect this change in the ui.

**Comment by MennoVink** [comment]
Added new event type and handling of the event in Resolume 7.4
