### ISSUE TITLE
Building a host

### ISSUE THREAD

**Issue by rsodre** [resolume/ffgl#53]
Hi!

If want to build a host that supports my FFGL 2.1 plugns, is the host source code I need in this repository too? Is there any example?

Roger

**Comment by rsodre** [comment]
Again, I ask if you can share a simple ffgl 2 host example, so I can use the plugins I developed on my apps too.
Or is it available anywhere else?

**Comment by rsodre** [comment]
I guess there is no public host code available that is compatible with this release.

I understand and support the need to evolve FFGL, but it's still an open source framework and there should be a parallel host repository. If we are developing FFGL plugins for Resolume, and there is no means to use on any other hosts because you refuse to share the host code, better stop calling it FFGL, because this has become a Resolume's proprietary thing now.
Or just add a simple host example, please.

At least point us to the last host repository that it was compatible with.

**Comment by MennoVink** [comment]
sorry for the delay with the answer, i'm only looking at github while working on ffgl and that isn't very often ;)

You are right that there is no public host code available. ffgl hosting implementations are very application specific, for example in Resolume, ffgl parameters are immediately translated to the objects that enable osc/dmx control/animation/etc. A host demo would just be a c++ wrapper around the ffgl opcodes and their argument structures. For us there just isn't enough interest in building ffgl hosts that it would warrant the time investment.

The information you need is right there in the FFGL.cpp though, i dont think it is as difficult as you make it out to be.
1. You start off by LoadLibraryExW the dll
2. You get the plugMain pointer using GetProcAddress
3. Init the library using FF_INITIALISE_V2, matching with a FF_DEINITIALISE
4. Then you could iterate over the parameters using FF_GET_NUM_PARAMETERS
5. Get parameter specific information using FF_GET_PARAMETER_*** opcodes
6. Probably you also want to create an actual instance using FF_INSTANTIATE_GL, mirrorred by FF_DEINSTANTIATE_GL
7. And render it using FF_CONNECT, mirrorred by FF_DISCONNECT and FF_RESIZE / FF_PROCESS_OPENGL in the middle

Sure, it requires a bit of figuring out, peeking into the FFGL.cpp to see what arguments it expects and returns. You'll also need to create an OpenGL context for which there are already several good tutorials out there.

**Comment by rsodre** [comment]
Thanks for the tips @MennoVink
