### ISSUE TITLE
Add method for updating the parameters on-fly

### ISSUE THREAD

**Issue by rytai** [resolume/ffgl#63]
Currently it's not possible to hide non-relevant parameters or change "option"-parameter infos.

I would use this for creating drop-down dialogs that have dynamic options.

Is this even possible to implement in FFGL, or should it be done in Resolume?

I tried to modify FFGLPluginManager.cpp's params struct directly, but the changes won't propagate to UI.

**Comment by MennoVink** [comment]
Dynamic param visibility is actually supported. You need to send the param visibility change events in order for Resolume to pick it up.
I'm not sure how you'd do dynamic element names in resolume, but ffgl does not support this currently. It should be easy to add this to ffgl itself, but support for it would need to be added in Resolume as well and i'm not sure how difficult that'd be.

**Comment by MennoVink** [comment]
Implemented in the master branch. Will require Resolume 7.4.1. Call SetParamElements to change the elements, send the event if you want Resolume to update the ui.
