### ISSUE TITLE
Add Workflow Tips to Readme? 

### ISSUE THREAD

**Issue by wyhinton** [resolume/ffgl#66]
It'd be great if the Readme included more information about an efficient pipeline for testing your plugins. For example, it's a paint to move generated .dll to the documents/extra effects folder, users can just add the release directory in the video>FreeFame (FFGL) Plugins Directory setting. 

Also, in order for updates to appear in the .dll must one manually close Resolume, delete the .dll, build the plugin again again, then open Resolume again? This is also pretty inefficient. 

Would appreciate the developer's or any community members thoughts/tips/tricks.

**Comment by MennoVink** [comment]
The readme contains a link to the wiki that explains the points you have mentioned. The [convenience tips page](https://github.com/resolume/ffgl/wiki/4.-Convenience-tips) is especially useful in explaining this.

**Comment by wyhinton** [comment]
I see, these are helpful. I think I'm a little thrown by the welcome page for the wiki being empty, I though you all just hadn't gotten around to adding to it yet, but I see on the right there are some entries added. I think it would improve the wiki legibility to include a table of contents in the wiki's welcome page (https://github.com/resolume/ffgl/wiki)
