### ISSUE TITLE
AddSubtract example - member shadowing

### ISSUE THREAD

**Issue by hepiyellow** [resolume/ffgl#68]
Hi,

I am kind of new to C++ programming, but isn't the `AddSubtract` example definition of the `shader` and `quad` member, shadows the `Plugin`'s (Base class)  members with the same name?

https://github.com/resolume/ffgl/blob/27c827e1f25896b834320eef649b9b661a6c2ed2/source/plugins/AddSubtract/AddSubtract.h#L17

**Comment by MennoVink** [comment]
While this is perfectly valid it's not as clear. I've made the add subtract example also use basic ffgl just like the other examples to make it easier to understand.
