### ISSUE TITLE
FFGL Testbed - what is the viewport dimensions?

### ISSUE THREAD

**Issue by hepiyellow** [resolume/ffgl#70]
It would be nice to know the viewport dimensions that are used.
I saw that the default input png is 1280x720
but when checking what I get in `FFGLViewportStruct* vp` that I get in `InitGL()` it yields 512x512.

a) Could we see the viewport dimensions in the UI?
b) Is the 512x512 correct or it is just a stub?

**Comment by MennoVink** [comment]
I'm assuming this is about the testbed.
The testbed should use the resolution for the input image as it's viewport dimensions. 512x512 for init is indeed incorrect and i'll fix that with next update.

**Comment by MennoVink** [comment]
Next release will provide the correct viewport dimensions during instantiation as well as show some host information in the left panel.
