### ISSUE TITLE
Fbo plugin crash when play and select the same clip with different dimensions

### ISSUE THREAD

**Issue by piotrus04** [resolume/ffgl#73]
Hi, 
Anybody has an example for rendering to texture in the processopengl function ?

I would like the effet to do :
output = inputTexture[0] + the previously rendered frame.

I made it working but when i both launch the clip in Avenue and select it to see the clip in the preview window, Avenue's memory suddenly grows in Gb and finally crash the computer. This happens because the dimension of the preview and the layer is not the same. Fbo seems to be recreated every frame.
Not sure if i programmed it correctly...
Any example ? thanks for all

**Comment by jorisdejong** [comment]
It's kind of hard to read the formatting, but one thing that stands out is that CFFGLPlugin::Resize is supposed to be callback, called by the host when the viewport changes dimensions. But you're also calling it directly at the beginning of ASlider::ProcessOpenGL. You also call ASlider::resolutionChanged at different times with either the viewport and inputtexture dimensions, which could cause it to return true repeatedly if those are not the same

**Comment by piotrus04** [comment]
Sorry for the formatting and thanks for your answer.
ok, i ll try to use the standard callback CFFGLPlugin::Resize
thanks

**Comment by jorisdejong** [comment]
No problem, hope it helps!

**Comment by piotrus04** [comment]
i am quite struggling, it crash when i remove my dimensionhaschanged function.

i would really appreciate if you can provide a working example of how to use the fbo in the processopengl function.
How possible it is to store the picture so that we can use it on the next render. Like the "Trails" effect does in Resolume.

if you have a bit of time for that...

**Comment by jorisdejong** [comment]
If you put up your current code on Github somewhere so it's easy to pull
and run on my end, I'll be happy to take a look at it

**Comment by piotrus04** [comment]
Hi Happy new year :)
here is the code easy to pull
https://github.com/piotrus04/aslider
